name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - name: get diff
        run: |
          git diff --name-status HEAD^
          echo $HOME
          git pull 
          git log
          git diff --name-status HEAD^
          echo "======================"
          git branch
          git remote -v
          echo "======================"
          git diff 
          pwd
          git status
          ls -1
