name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - name: get diff
        run: |
          git diff HEAD~1 . | grep ^diff | cut -f3 -d\  | cut -c 3- > ./diff.txt
          echo $HOME
          git log
          ehco "======================"
          git diff 
          pwd
          git status
          ls -1
